import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const Vazir = localFont({
  src: "./fonts/Vazir.woff2",
  display: "swap",
});

// type DefaultTemplateString = {
//   default: string;
//   template: string; // Required property
// };

export const metadata: Metadata = {
  title: {
    default: "Quiz App",
    template: "%s - Quiz App", // Adjust your template as needed
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa-IR" dir="rtl" className={Vazir.className}>
      <body>{children}</body>
    </html>
  );
}
